sonar.projectKey=Orden.example:Orden
sonar.projectName=SmartLogix — Microservicio Orden
sonar.organization=benjazzx
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/config/**,**/OrdenApplication.java
sonar.coverage.exclusions=**/config/**,**/OrdenApplication.java
sonar.java.source=21
sonar.sourceEncoding=UTF-8
