events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    upstream rol-service      { server rol-service:8081; }
    upstream users-service    { server users-service:8082; }
    upstream inventario-service { server inventario-service:8083; }
    upstream orden-service    { server orden-service:8084; }
    upstream producto-service { server producto-service:8085; }
    upstream estado-service   { server estado-service:8082; }

    server {
        listen 80;

        # Redirige /api/roles/** → microservicio Rol
        location /api/roles {
            proxy_pass http://rol-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige /api/users/** → microservicio Users
        location /api/users {
            proxy_pass http://users-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige /api/inventario/** → microservicio Inventario
        location /api/inventario {
            proxy_pass http://inventario-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige /api/ordenes/** → microservicio Orden
        location /api/ordenes {
            proxy_pass http://orden-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige /api/productos/** → microservicio Producto
        location /api/productos {
            proxy_pass http://producto-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirige /api/estados/** → microservicio Estado
        location /api/estados {
            proxy_pass http://estado-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
