sonar.projectKey=SmartLogix-Rol
sonar.projectName=SmartLogix — Microservicio Rol
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN}
sonar.java.source=21
sonar.sourceEncoding=UTF-8
