spring.application.name=Rol
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Rol
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.function.definition=processUserRegistration
spring.cloud.stream.bindings.processUserRegistration-in-0.destination=user-registered-topic
spring.cloud.stream.bindings.processUserRegistration-in-0.group=rol-group
spring.cloud.stream.bindings.processUserRegistration-out-0.destination=role-assigned-topic
spring.cloud.stream.kafka.binder.brokers=localhost:9092